#!/usr/bin/env bash
# init-config.sh — deterministic writer + inference for .qa/config.json.
# The agent asks the user the gaps, then calls this to WRITE valid JSON (so the
# config is never hand-authored / malformed). `--suggest` prints inferred defaults
# the agent uses to pre-fill its questions.
#
# Write mode:
#   init-config.sh --base-url URL [--environment auto|disposable|production]
#                  [--repos "a,b"] [--api-origin ORIGIN] [--storage-state PATH]
#                  [--allow-writes true|false] [--allow-crawl true|false]
#                  [--seedable-marker NAME] [--out PATH]
# Inference mode:
#   init-config.sh --suggest        # prints {baseUrl, repos, stack} as JSON
set -uo pipefail

SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
DETECT="$SELF_DIR/../../detecting-stack-profile/scripts/detect-stack.sh"

BASE_URL=""; ENVIRONMENT="auto"; REPOS="."; API_ORIGIN=""
STORAGE_STATE=".qa/auth/storageState.json"; ALLOW_WRITES="false"; ALLOW_CRAWL="false"
SEEDABLE_MARKER="QA_DISPOSABLE_ENV"; OUT=".qa/config.json"; SUGGEST=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url)        BASE_URL="$2"; shift 2 ;;
    --environment)     ENVIRONMENT="$2"; shift 2 ;;
    --repos)           REPOS="$2"; shift 2 ;;
    --api-origin)      API_ORIGIN="$2"; shift 2 ;;
    --storage-state)   STORAGE_STATE="$2"; shift 2 ;;
    --allow-writes)    ALLOW_WRITES="$2"; shift 2 ;;
    --allow-crawl)     ALLOW_CRAWL="$2"; shift 2 ;;
    --seedable-marker) SEEDABLE_MARKER="$2"; shift 2 ;;
    --out)             OUT="$2"; shift 2 ;;
    --suggest)         SUGGEST=1; shift ;;
    *) echo "init-config: unknown arg: $1" >&2; exit 2 ;;
  esac
done

have() { command -v "$1" >/dev/null 2>&1; }
have jq || { echo "init-config: jq is required" >&2; exit 3; }

# ── inference (--suggest) ─────────────────────────────────────────────────────
infer_base_url() {
  # DDEV: read the project name → https://<name>.ddev.site
  if [[ -f ".ddev/config.yaml" ]]; then
    local name; name="$(grep -E '^name:' .ddev/config.yaml 2>/dev/null | head -1 | sed 's/^name:[[:space:]]*//; s/[[:space:]]*$//; s/^["'\'']//; s/["'\'']$//')"
    [[ -n "$name" ]] && { echo "https://${name}.ddev.site"; return; }
  fi
  # Laravel artisan serve default; Vite/Node default; else blank (ask the user).
  if [[ -f "artisan" ]]; then echo "http://localhost:8000"; return; fi
  if [[ -f "package.json" ]]; then echo "http://localhost:3000"; return; fi
  echo ""
}

if [[ "$SUGGEST" -eq 1 ]]; then
  guess_url="$(infer_base_url)"
  stack="unknown"
  if [[ -x "$DETECT" ]]; then
    stack="$(QA_REPOS="." bash "$DETECT" --no-runtime 2>/dev/null | jq -r '.components[0].framework // "unknown"')"
  fi
  jq -n --arg url "$guess_url" --arg repos "." --arg stack "$stack" \
    '{baseUrl:$url, repos:$repos, stack:$stack}'
  exit 0
fi

# ── write mode ────────────────────────────────────────────────────────────────
[[ -n "$BASE_URL" ]] || { echo "init-config: --base-url is required (or use --suggest)" >&2; exit 2; }

# repos CSV → array of {role, path}. First entry is the backend (monolith default).
repos_json="$(jq -n '[]')"
IFS=',' read -ra rps <<< "$REPOS"
first=1
for rp in "${rps[@]}"; do
  rp="${rp// /}"; [[ -z "$rp" ]] && continue
  role="reference"; [[ "$first" -eq 1 ]] && { role="backend"; first=0; }
  repos_json="$(jq -c --arg role "$role" --arg path "$rp" '. + [{role:$role, path:$path}]' <<< "$repos_json")"
done

mkdir -p "$(dirname "$OUT")" 2>/dev/null || true

jq -n \
  --arg base "$BASE_URL" --arg api "$API_ORIGIN" --arg ss "$STORAGE_STATE" \
  --arg env "$ENVIRONMENT" --arg marker "$SEEDABLE_MARKER" \
  --argjson repos "$repos_json" \
  --argjson writes "$ALLOW_WRITES" --argjson crawl "$ALLOW_CRAWL" '{
  "_doc": "Auto-generated by bootstrapping-qa-config. Edit freely; re-run /qa-run to use it.",
  baseUrl: $base,
  apiOrigin: $api,
  auth: { storageState: $ss },
  drivers: [ { id: "managed", server: (env.QA_DRIVER_SERVER // "playwright"), preset: "managed" } ],
  maxParallel: 3,
  repos: $repos,
  allowApiWrites: $writes,
  seedableEnvMarker: $marker,
  environment: $env,
  allowBlackboxCrawl: $crawl,
  fingerprintPaths: ["/openapi.json", "/swagger/v1/swagger.json"],
  noProbePaths: [],
  crawlDenyPatterns: [],
  maxRequestsPerSecond: 2,
  memory: { backend: "file" },
  humanInteraction: { enforce: true, saveSession: false, maxOptOutRate: 0.2, sessionLogDir: ".playwright-mcp" }
}' > "$OUT"

# Real-project side effects only when writing into an actual `.qa/` dir
# (skipped when tests write to a temp file).
qadir="$(dirname "$OUT")"
if [[ "$(basename "$qadir")" == ".qa" ]]; then
  mkdir -p "$qadir/auth" "$qadir/runs" 2>/dev/null || true
  if [[ -d .git || -f .gitignore ]]; then
    if ! grep -qxF '.qa/' .gitignore 2>/dev/null; then
      printf '\n# qa-e2e-pilot per-project state\n.qa/\n' >> .gitignore
    fi
  fi
fi

echo "Wrote $OUT"
